<?php
/**
 * Title: Showcase Element
 *
 * Description: Defines custom post type "showcase".
 *                Defines action to be done when element "showcase" is active.
 *
 * Please do not edit this file. This file is part of the CyberChimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v3.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

// Don't load directly
if( !defined( 'ABSPATH' ) ) {
	die( '-1' );
}

if( !class_exists( 'CyberChimpsShowcase' ) ) {
	class CyberChimpsShowcase {

		protected static $instance;
		public $options;

		/* Static Singleton Factory Method */
		public static function instance() {
			if( !isset( self::$instance ) ) {
				$className      = __CLASS__;
				self::$instance = new $className;
			}

			return self::$instance;
		}

		/**
		 * Initializes plugin variables and sets up WordPress hooks/actions.
		 *
		 * @return void
		 */
		protected function __construct() {
			add_action( 'showcase', array( $this, 'render_display' ) );
			$this->options = get_option( 'cyberchimps_options' );
			add_action( 'init', array( $this, 'cyberchimps_init_showcase_post_type' ) );
		}

		//Define Custom post type
		function cyberchimps_init_showcase_post_type() {

			register_post_type( 'showcase_posts',
			                    array(
				                    'labels'      => array(
					                    'name'               => __( 'Showcase', 'cyberchimps_elements' ),
					                    'singular_name'      => __( 'Showcase item', 'cyberchimps_elements' ),
					                    'add_new_item'       => __( 'Add new Showcase item', 'cyberchimps_elements' ),
					                    'edit_item'          => __( 'Edit Showcase item', 'cyberchimps_elements' ),
					                    'new_item'           => __( 'New Showcase item', 'cyberchimps_elements' ),
					                    'view_item'          => __( 'View Showcase item', 'cyberchimps_elements' ),
					                    'search_items'       => __( 'Search Showcase items', 'cyberchimps_elements' ),
					                    'not_found'          => __( 'No Showcase items found', 'cyberchimps_elements' ),
					                    'not_found_in_trash' => __( 'No Showcase items found in trash', 'cyberchimps_elements' )
				                    ),
				                    'public'      => true,
				                    'show_ui'     => true,
				                    'supports'    => array( 'custom-fields', 'title' ),
				                    'taxonomies'  => array( 'showcase_categories' ),
				                    'has_archive' => false,
				                    //'menu_icon'   => get_template_directory_uri() . '/cyberchimps/lib/images/custom-types/carousel.png',
				                    'rewrite'     => false
			                    )
			);

			$labels = array(
				'name'              => _x( 'Showcase Categories', 'taxonomy general name', 'cyberchimps_elements' ),
				'singular_name'     => _x( 'Showcase Category', 'taxonomy singular name', 'cyberchimps_elements' ),
				'search_items'      => __( 'Search Showcase', 'cyberchimps_elements' ),
				'all_items'         => __( 'All Showcase', 'cyberchimps_elements' ),
				'parent_item'       => __( 'Showcase Category', 'cyberchimps_elements' ),
				'parent_item_colon' => __( 'Showcase Category:', 'cyberchimps_elements' ),
				'edit_item'         => __( 'Edit Showcase Category', 'cyberchimps_elements' ),
				'update_item'       => __( 'Update Showcase Category', 'cyberchimps_elements' ),
				'add_new_item'      => __( 'Add New Showcase Category', 'cyberchimps_elements' ),
				'new_item_name'     => __( 'New Showcase Category Name', 'cyberchimps_elements' ),
				'menu_name'         => __( 'Showcase Category', 'cyberchimps_elements' )
			);

			register_taxonomy( 'showcase_categories', array( 'showcase_posts' ), array(
				'public'            => true,
				'show_in_nav_menus' => false,
				'hierarchical'      => true,
				'labels'            => $labels,
				'show_ui'           => true
			) );

			/**
			 * Set up Meta Boxes on Box custom post type
			 */

			$showcase_fields = array( array(
				'type'  => 'single_image',
				'id'    => 'showcase_post_image',
				'class' => '',
				'name'  => __( 'Showcase Image', 'cyberchimps_elements' ),
				'std'   => ''
			),
				array(
					'type'  => 'text',
					'id'    => 'showcase_author_name',
					'class' => '',
					'name'  => __( 'Showcase Author Name', 'cyberchimps_elements' )
				),
				array(
					'type'  => 'text',
					'id'    => 'showcase_text',
					'class' => '',
					'name'  => __( 'Showcase Text', 'cyberchimps_elements' )
				),

			);
			/*
			 * configure your meta box
			 */
			$showcase_config = array(
				'id'             => 'showcase_options', // meta box id, unique per meta box
				'title'          => __( 'Featured Post Showcase', 'cyberchimps_elements' ), // meta box title
				'pages'          => array( 'showcase_posts' ), // post types, accept custom post types as well, default is array('post'); optional
				'context'        => 'normal', // where the meta box appear: normal (default), advanced, side; optional
				'priority'       => 'high', // order of meta box: high (default), low; optional
				'fields'         => $showcase_fields, // list of meta fields (can be added by field arrays)
				'local_images'   => false, // Use local or hosted images (meta box images for add/remove)
				'use_with_theme' => true //change path if used with theme set to true, false for a plugin or anything else for a custom path(default false).
			);

			/*
			 * Initiate your meta box
			 */
			$showcase_meta = new Cyberchimps_Meta_Box( $showcase_config );

			/**
			 * Set up Meta Boxes on Page
			 *
			 */

			$showcase_terms = get_terms( 'showcase_categories', 'hide_empty=0' );
			if( !is_wp_error( $showcase_terms ) ) {
				foreach( $showcase_terms as $term ) {
					$showcase_options[$term->slug] = $term->name;
				}
			}
			else {
				$showcase_options = null;
			}

			$page_fields = array(
				array(
					'type'    => 'select',
					'id'      => 'showcase_category',
					'class'   => '',
					'name'    => __( 'Showcase Category', 'cyberchimps_elements' ),
					'options' => ( isset( $showcase_options ) ) ? $showcase_options : array( 'cc_no_options' => __( 'You need to create a Category', 'cyberchimps_core' ) )
				),
				array(
					'type'    => 'single_image',
					'id'      => 'showcase_background',
					'desc'    => __('Best suited image size is 1280px * 375px', 'cyberchimps_elements'),
					'class'   => '',
					'name'    => __( 'Showcase Background', 'cyberchimps_elements' )
				)

			);
			/*
			 * configure your meta box
			 */
			$page_config = array(
				'id'             => 'showcase_options', // meta box id, unique per meta box
				'title'          => __( 'Showcase Options', 'cyberchimps_elements' ), // meta box title
				'pages'          => array( 'page' ), // post types, accept custom post types as well, default is array('post'); optional
				'context'        => 'normal', // where the meta box appear: normal (default), advanced, side; optional
				'priority'       => 'high', // order of meta box: high (default), low; optional
				'fields'         => apply_filters( 'cyberchimps_showcase_metabox_fields', $page_fields, 'showcase' ), // list of meta fields (can be added by field arrays)
				'local_images'   => false, // Use local or hosted images (meta box images for add/remove)
				'use_with_theme' => true //change path if used with theme set to true, false for a plugin or anything else for a custom path(default false).
			);

			/*
			 * Initiate your meta box
			 */
			$page_meta = new Cyberchimps_Meta_Box( $page_config );
		}

		/**
		 * Puts markup for showcase
		 *
		 * @return void
		 */
		public function render_display() {

			// Get the default image of carousel
			$default = get_template_directory_uri() . apply_filters( 'cyberchimps_showcase_img', '/cyberchimps/lib/images/showcase.jpg' );
			$custombackground = cyberchimps_get_option('showcase_background');

			if( is_page() ) {
				$customcategory = get_post_meta( get_the_ID(), 'showcase_category', true );
				$custombackground = get_post_meta( get_the_ID(), 'showcase_background', true );			

				if($custombackground == ""){
?>
					<style type="text/css" media="all">
						#showcase_section{ 
							background : url("<?php echo $default; ?>") no-repeat scroll 0 0 / cover;
						}	
					</style>
<?php
				}
				else{
?>
					<style type="text/css" media="all">
						#showcase_section{ 
							background : url("<?php echo $custombackground; ?>") no-repeat scroll 0 0 / cover;
						}	
					</style>
<?php
				}			
			}

			else {
				$customcategory_obj     = ( isset( $this->options['showcase_categories'] ) ) ? get_term( $this->options['showcase_categories'], 'showcase_categories' ) : '';
				$customcategory     = ( isset( $this->options['showcase_categories'] ) ) ? $customcategory_obj->slug : '';
				$custombackground        = $this->options['showcase_background'];
			}
	
				$args = array(
					'numberposts'         => -1,
					'offset'              => 0,
					'showcase_categories' => $customcategory,
					'showcase_background' => $custombackground,
					'orderby'             => 'post_date',
					'order'               => 'ASC',
					'post_type'           => 'showcase_posts',
					'post_status'         => 'publish',
					'suppress_filters'    => false
				);
		
				$showcase_posts = get_posts( $args );
			?>
			<div id="showcase_container" class="row">
				<div id="showcase" class="col-lg-12">
					<div id="gallery-showcase" class="carousel slide portfolio-section" data-ride="carousel">

						<?php

						if( $showcase_posts ) { 
							$slide_counter1 = 1; ?>
							 <div role="listbox" class="carousel-inner">

						<?php	foreach( $showcase_posts as $post ) {

								/* Post-specific variables */
								$image    = get_post_meta( $post->ID, 'showcase_post_image', true );
								$title    = $post->post_title;
								$showcase_author    = get_post_meta( $post->ID, 'showcase_author_name', true );
								$showcase_text    = get_post_meta( $post->ID, 'showcase_text', true );
						?>
								
								<div class="showcase_main_div item <?php echo ( $slide_counter1 == 1 ) ? "active" : ""; ?>">
	                                                            <div class="showcase_img col-lg-12 "><img src="<?php echo $image; ?>" alt="<?php echo $title; ?>"/></div>
								    <div class="showcase_author col-lg-12">
									<?php echo $showcase_author; ?>
								    </div>
								    <div class="showcase_text col-lg-12">
									<?php echo $showcase_text; ?>
								    </div>
								    
								</div>
								
								
						<?php
							$slide_counter1++;
							}// end of foreach ?>
							
							</div> <!-- end of carousel-inner-->
							<a class="carousel-control left slider-left" href="#gallery-showcase" data-slide="prev">
								<span class="glyphicon glyphicon-chevron-left"></span>
							</a>
							<a class="carousel-control right slider-right" href="#gallery-showcase" data-slide="next">
								<span class="glyphicon glyphicon-chevron-right"></span>
							</a>
					<?php	} // end of if
						else {
							$image = get_template_directory_uri() . "/cyberchimps/lib/images/portfolio.jpg";
							?>
							<div class="showcase_main_div item">
		                            			<div class="showcase_img col-lg-12 ">	
									<img src="<?php echo $image; ?>" alt="<?php if(!empty($title)) echo $title; ?>"/>
								</div>
								<div class="showcase_author col-lg-12">Showcase Author
								</div>
								<div class="showcase_text col-lg-12">Sample Text
								</div>
							</div>

						<?php } ?>
						</div>
					</div>
					<!-- .es-carousel -->
				</div>
				<!-- #carousel -->
			</div><!-- #container -->
		<?php
		}
	}
}
CyberChimpsShowcase::instance();
