<?php
/**
 * Theme Functions
 *
 * Please do not edit this file. This file is part of the CyberChimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v3.0 (or later)
 * @link     http://www.cyberchimps.com/
 */
// Don't load directly
if ( ! defined( 'ABSPATH' ) ) {
	die( '-1' );
}

if ( ! class_exists( 'CyberChimpsBoxesLayout' ) ) {

	class CyberChimpsBoxesLayout {

		protected static $instance;
		public $options;

		/* Static Singleton Factory Method */

		public static function instance() {
			if ( ! isset( self::$instance ) ) {
				$className = __CLASS__;
				self::$instance = new $className;
			}

			return self::$instance;
		} //end of instance

		/**
		 * Initializes plugin variables and sets up WordPress hooks/actions.
		 *
		 * @return void
		 */
		protected function __construct() {
			add_action( 'init', array( $this, 'meta_box' ) );
			$this->options = get_option( 'cyberchimps_options' );
		} //end of construct

		public function meta_box() {

			$page_fields = array(
				array(
					'type'    => 'select',
					'id'      => 'cyberchimps_slider_type',
					'class'   => 'select-hide',
					'name'    => __( 'Select Box Template Type', 'one-page-business-pro' ),
					'options' => array( 'service' => __( 'Service Layout', 'one-page-business-pro' ),'portfolio' => __( 'Portfolio Layout', 'one-page-business-pro' ), 'testimonial' => __( 'Testimonial Layout', 'one-page-business-pro' ), 'team' => __( 'Team Layout', 'one-page-business-pro' ) )),



/* *********************** Services Layout Start ******************************* */				
				array(
					'type'  => 'single_image',
					'id'    => 'service_cyberchimps_box_image',
					'name'  => __( 'Box Image', 'one-page-business-pro' ),
					'class'   => 'service-select'
				),
				array(
					'name'    => __( 'Description', 'one-page-business-pro' ),
					'id'      => 'service_cyberchimps_box_description',
					'class'   => 'service-select',
					'type'    => 'editor'
				),
/* *********************** Services Layout End ******************************* */		


/* *********************** Portfolio Layout Start ******************************* */						
				array(
					'type'  => 'single_image',
					'id'    => 'portfolio_cyberchimps_box_image',
					'name'  => __( 'Box Image', 'one-page-business-pro' ),
					'class'   => 'portfolio-select'
				),
				array(
					'name'    => __( 'Short Description', 'one-page-business-pro' ),
					'id'      => 'portfolio_cyberchimps_box_short_description',
					'class'   => 'portfolio-select',
					'type'    => 'text'
				),
				array(
					'name'    => __( 'Description', 'one-page-business-pro' ),
					'id'      => 'portfolio_cyberchimps_box_description',
					'class'   => 'portfolio-select',
					'type'    => 'editor'
				),
/* *********************** Portfolio Layout End ******************************* */		
					
		


/* *********************** Team Layout Start ******************************* */				
				array(
					'type'  => 'single_image',
					'id'    => 'team_cyberchimps_box_image',
					'name'  => __( 'Team Member Image', 'one-page-business-pro' ),
					'class'   => 'team-select'
				),
				array(
					'name'    => __( 'Team Member Description', 'one-page-business-pro' ),
					'id'      => 'team_cyberchimps_box_description',
					'class'   => 'team-select',
					'type'    => 'editor'
				),
				array(
					'name'    => __( 'Facebook URL', 'one-page-business-pro' ),
					'id'      => 'team_cyberchimps_box_facebook_url',
					'class'   => 'team-select',
					'type'    => 'text'
				),
				array(
					'name'    => __( 'Twitter URL', 'one-page-business-pro' ),
					'id'      => 'team_cyberchimps_box_twitter_url',
					'class'   => 'team-select',
					'type'    => 'text'
				),
				array(
					'name'    => __( 'Google URL', 'one-page-business-pro' ),
					'id'      => 'team_cyberchimps_box_google_url',
					'class'   => 'team-select',
					'type'    => 'text'
				),

/* *********************** Team Layout End ******************************* */				
				


/* *********************** Testimonial Layout START ******************************* */				
					
					array(
							'name'    => __( 'Description', 'one-page-business-pro' ),
							'id'      => 'testimonial_cyberchimps_box_description',
							'class'   => 'testimonial-select',
							'type'    => 'editor'
					),
/* *********************** Testimonial Layout END  ******************************* */			
			);

		
			
			
			
			/*
			 * configure your meta box
			 */
			$page_config = array(
				'id'             => 'custom_box_options', // meta box id, unique per meta box
				'title'          => __( 'Select Layout', 'cyberchimps_elements' ), // meta box title
				'pages'          => array( 'boxes' ), // post types, accept custom post types as well, default is array('post'); optional
				'context'        => 'normal', // where the meta box appear: normal (default), advanced, side; optional
				'priority'       => 'high', // order of meta box: high (default), low; optional
				'fields'         => apply_filters( 'cyberchimps_reservation_metabox_fields', $page_fields, 'reservation' ), // list of meta fields (can be added by field arrays)
				'local_images'   => false, // Use local or hosted images (meta box images for add/remove)
				'use_with_theme' => true //change path if used with theme set to true, false for a plugin or anything else for a custom path(default false).
			);

			/*
			 * Initiate your meta box
			 */
			$page_meta = new Cyberchimps_Meta_Box( $page_config );
		}

	}
}
CyberChimpsBoxesLayout::instance();
