<?php
/**
 * Content Template
 *
 * Please do not edit this file. This file is part of the CyberChimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v3.0 (or later)
 * @link     http://www.cyberchimps.com/
 */
global $post_width;
?>
<?php if (!is_single() && !is_search() && !is_page() && !is_archive() && is_home())
{
		// Getting the cyberchimps options
		$layout_type = cyberchimps_get_option( 'sidebar_images', 'right_sidebar' );
		switch( $layout_type ) {
		case 'full_width' :
			$post_width = 'col-md-4';
			break;
		case 'right_sidebar' :
			$post_width = 'col-md-6';
			break;
		case 'left_sidebar' :
			$post_width = 'col-md-6';
			break;
		case 'content_middle' :
			$post_width = 'col-md-12';
			break;
		case 'left_right_sidebar' :
			$post_width = 'col-md-12';
			break;
		}
		$read_more_data = cyberchimps_get_option('blog_read_more_text');	
		$blog_length_excerpt = cyberchimps_get_option('blog_excerpt_length');
?>
<article id="post-<?php the_ID(); ?>" <?php post_class('post_article'.' '.$post_width); ?>>
	<?php if( cyberchimps_get_option( 'post_excerpts', 0 ) != 0 ): ?>
		<div class="entry-summary">
			<?php cyberchimps_featured_image();
			cyberchimps_post_format_icon(); ?>
			<header class="entry-header">
				<?php 
				echo ( 'post' == get_post_type()) ? '<h3 class="entry-title">' : '<h1 class="entry-title">';
				if ( 'page' == get_post_type() ) : 
					// get the page title toggle option
					$page_title = get_post_meta( get_the_ID(), 'cyberchimps_page_title_toggle', true);
					if( $page_title == "1" || $page_title == "" ) :
						( get_the_title() )? the_title() : the_permalink();
					endif;
				else :
				?>
					<a href="<?php the_permalink(); ?>" title="<?php printf( esc_attr__( 'Permalink to %s', 'one-page-business-pro' ), the_title_attribute( 'echo=0' ) ); ?>" rel="bookmark">
						<?php ( get_the_title() )? the_title() : the_permalink(); ?>
					</a>
				<?php
				endif; 

				echo ( 'post' == get_post_type()) ? '</h3>' : '</h1>'; ?>
				<div class="entry-meta-top">				
					<div class="row">
						<div class="col-lg-12 main_posted_by">
							<?php cyberchimps_posted_by(); ?>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							<?php cyberchimps_posted_in(); ?>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							<?php if ( 'post' == get_post_type() && cyberchimps_get_option( 'post_byline_tags', 1 ) ) :
								cyberchimps_post_tags();
							  endif; // End if 'post' == get_post_type() ?>
						</div>
					</div>
				</div>

				<?php if ( 'post' == get_post_type() ) : ?>
					<div class="post_excerpt">
						<?php echo wp_trim_words( get_the_content(), $blog_length_excerpt, ' ...' ); ?>
					</div>
					<div class="entry-meta">
						<div class="row">
							<div class="col-lg-7">
								<?php cyberchimps_posted_on();?>
							</div>
							<div class="col-lg-5">
								<?php cyberchimps_post_comments();?>
							</div>
						</div>
												
						<div class="row">
							<div class="col-lg-12 read_more_data">
								<a href="<?php the_permalink(); ?>" title="<?php printf( esc_attr__( 'Permalink to %s', 'one-page-business-pro' ), the_title_attribute( 'echo=0' ) ); ?>" rel="bookmark"> <?php echo $read_more_data; ?>
								</a> 
							</div>
						</div>
					</div><!-- .entry-meta -->
				<?php endif; ?>
			</header><!-- .entry-header -->
		</div> 
<?php //endif;
else:
?>
	<div class="entry-content">
		<?php cyberchimps_featured_image();
			cyberchimps_post_format_icon(); ?>
		<header class="entry-header">
				<?php 
				echo ( 'post' == get_post_type()) ? '<h3 class="entry-title">' : '<h1 class="entry-title">';
				if ( 'page' == get_post_type() ) : 
					// get the page title toggle option
					$page_title = get_post_meta( get_the_ID(), 'cyberchimps_page_title_toggle', true);
					if( $page_title == "1" || $page_title == "" ) :
						( get_the_title() )? the_title() : the_permalink();
					endif;
				else :
				?>
					<a href="<?php the_permalink(); ?>" title="<?php printf( esc_attr__( 'Permalink to %s', 'one-page-business-pro' ), the_title_attribute( 'echo=0' ) ); ?>" rel="bookmark">
						<?php ( get_the_title() )? the_title() : the_permalink(); ?>
					</a>
				<?php
				endif; 
				echo ( 'post' == get_post_type()) ? '</h3>' : '</h1>'; ?>
				<div class="entry-meta-top">				
					<div class="row">
						<div class="col-lg-12 main_posted_by">
							<?php cyberchimps_posted_by(); ?>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							<?php cyberchimps_posted_in(); ?>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							<?php if ( 'post' == get_post_type() && cyberchimps_get_option( 'post_byline_tags', 1 ) ) :
								cyberchimps_post_tags();
							  endif; // End if 'post' == get_post_type() ?>
						</div>
					</div>
				</div>
			<?php 
					if ( 'post' == get_post_type() ) : ?>
					<div class="post_content">
						<?php the_content( __( 'Continue reading', 'one-page-business-pro' ) . '<span class="meta-nav">&rarr;</span>' ); ?>
					</div>
					<div class="entry-meta">
						<div class="row">
							<div class="col-lg-7">
								<?php cyberchimps_posted_on();?>
							</div>
							<div class="col-lg-5">
								<?php cyberchimps_post_comments();?>
							</div>
						</div>
													
						
					</div><!-- .entry-meta --><?php endif; ?>
			</header><!-- .entry-header -->
			<?php edit_post_link( __( 'Edit', 'one-page-business-pro' ), '<span class="edit-link">', '</span>' ); ?>
			<?php wp_link_pages( array( 'before' => '<div class="page-links">' . __( 'Pages:', 'one-page-business-pro' ), 'after' => '</div>' ) ); ?>
		</div><!-- .entry-content -->
    	<?php
endif; ?>
</article>
<?php 
}
/*==================================================================================================================================================================*/
elseif(is_archive())
{
		// Getting the cyberchimps options
		$layout_type = cyberchimps_get_option( 'sidebar_images', 'right_sidebar' );
		switch( $layout_type ) {
		case 'full_width' :
			$post_width = 'col-md-4';
			break;
		case 'right_sidebar' :
			$post_width = 'col-md-6';
			break;
		case 'left_sidebar' :
			$post_width = 'col-md-6';
			break;
		case 'content_middle' :
			$post_width = 'col-md-12';
			break;
		case 'left_right_sidebar' :
			$post_width = 'col-md-12';
			break;
		}
?>
<div id="column_width" class="<?php echo $post_width; ?>"></div>
<!-- Used by masonry to get column width -->
<div id="gutter_width"></div>
<!-- Used by masonry to get gutter width -->
<article id="post-<?php the_ID(); ?>" <?php post_class('post_article'.' '.$post_width); ?>>
	<?php if( cyberchimps_get_option( 'archive_post_excerpts', 0 ) != 0 ): ?>
		<div class="entry-summary">
			<?php cyberchimps_featured_image();
			cyberchimps_post_format_icon(); ?>
			<header class="entry-header">
				<?php 
				echo ( 'post' == get_post_type()) ? '<h3 class="entry-title">' : '<h1 class="entry-title">';
				if ( 'page' == get_post_type() ) : 
					// get the page title toggle option
					$page_title = get_post_meta( get_the_ID(), 'cyberchimps_page_title_toggle', true);
					if( $page_title == "1" || $page_title == "" ) :
						( get_the_title() )? the_title() : the_permalink();
					endif;
				else :
				?>
					<a href="<?php the_permalink(); ?>" title="<?php printf( esc_attr__( 'Permalink to %s', 'one-page-business-pro' ), the_title_attribute( 'echo=0' ) ); ?>" rel="bookmark">
						<?php ( get_the_title() )? the_title() : the_permalink(); ?>
					</a>
				<?php
				endif; 

				echo ( 'post' == get_post_type()) ? '</h3>' : '</h1>'; ?>
				<div class="entry-meta-top">				
					<div class="row">
						<div class="col-lg-12 main_posted_by">
							<?php cyberchimps_posted_by(); ?>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							<?php cyberchimps_posted_in(); ?>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							<?php if ( 'post' == get_post_type() && cyberchimps_get_option( 'post_byline_tags', 1 ) ) :
								cyberchimps_post_tags();
							  endif; // End if 'post' == get_post_type() ?>
						</div>
					</div>
				</div>

				<?php if ( 'post' == get_post_type() ) : ?>
					<div class="post_excerpt">
						<?php echo wp_trim_words( get_the_content(), 55, ' ...' ); ?>
					</div>
					<div class="entry-meta">
						<div class="row">
							<div class="col-lg-7">
								<?php cyberchimps_posted_on();?>
							</div>
							<div class="col-lg-5">
								<?php cyberchimps_post_comments();?>
							</div>
						</div>
												
						<div class="row">
							<div class="col-lg-12 read_more_data">
								<a href="<?php the_permalink(); ?>" title="<?php printf( esc_attr__( 'Permalink to %s', 'one-page-business-pro' ), the_title_attribute( 'echo=0' ) ); ?>" rel="bookmark"> Read More...
								</a> 
							</div>
						</div>
					</div><!-- .entry-meta -->
				<?php endif; ?>
			</header><!-- .entry-header -->
		</div> 
<?php //endif;
else:
?>
	<div class="entry-content">
		<?php cyberchimps_featured_image();
			cyberchimps_post_format_icon(); ?>
		<header class="entry-header">
				<?php 
				echo ( 'post' == get_post_type()) ? '<h3 class="entry-title">' : '<h1 class="entry-title">';
				if ( 'page' == get_post_type() ) : 
					// get the page title toggle option
					$page_title = get_post_meta( get_the_ID(), 'cyberchimps_page_title_toggle', true);
					if( $page_title == "1" || $page_title == "" ) :
						( get_the_title() )? the_title() : the_permalink();
					endif;
				else :
				?>
					<a href="<?php the_permalink(); ?>" title="<?php printf( esc_attr__( 'Permalink to %s', 'one-page-business-pro' ), the_title_attribute( 'echo=0' ) ); ?>" rel="bookmark">
						<?php ( get_the_title() )? the_title() : the_permalink(); ?>
					</a>
				<?php
				endif; 
				echo ( 'post' == get_post_type()) ? '</h3>' : '</h1>'; ?>
				<div class="entry-meta-top">				
					<div class="row">
						<div class="col-lg-12 main_posted_by">
							<?php cyberchimps_posted_by(); ?>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							<?php cyberchimps_posted_in(); ?>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							<?php if ( 'post' == get_post_type() && cyberchimps_get_option( 'post_byline_tags', 1 ) ) :
								cyberchimps_post_tags();
							  endif; // End if 'post' == get_post_type() ?>
						</div>
					</div>
				</div>
			<?php 
					if ( 'post' == get_post_type() ) : ?>
					<div class="post_content">
						<?php the_content( __( 'Continue reading', 'one-page-business-pro' ) . '<span class="meta-nav">&rarr;</span>' ); ?>
					</div>
					<div class="entry-meta">
						<div class="row">
							<div class="col-lg-7">
								<?php cyberchimps_posted_on();?>
							</div>
							<div class="col-lg-5">
								<?php cyberchimps_post_comments();?>
							</div>
						</div>
													
						
					</div><!-- .entry-meta --><?php endif; ?>
			</header><!-- .entry-header -->
			<?php edit_post_link( __( 'Edit', 'one-page-business-pro' ), '<span class="edit-link">', '</span>' ); ?>
			<?php wp_link_pages( array( 'before' => '<div class="page-links">' . __( 'Pages:', 'one-page-business-pro' ), 'after' => '</div>' ) ); ?>
		</div><!-- .entry-content -->
    	<?php
endif; ?>
</article>
<?php
}
/*=======================================================================================================================================================*/
else
{
?>
<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
	<header class="entry-header">
		<div class="row fad_single_header">
			<div class="col-lg-11">
				<?php echo ( 'post' == get_post_type() && !is_single() || is_search() ) ? '<h2 class="entry-title">' : '<h1 class="entry-title">';
				if ( 'page' == get_post_type() ) : 
				// get the page title toggle option
				 $page_title = get_post_meta( get_the_ID(), 'cyberchimps_page_title_toggle', true);
				 
					if( is_search() ):
					?>
						<a href="<?php the_permalink(); ?>" title="<?php printf( esc_attr__( 'Permalink to %s', 'one-page-business-pro' ), the_title_attribute( 'echo=0' ) ); ?>" rel="bookmark">
								<?php ( get_the_title() )? the_title() : the_permalink(); ?>
						</a>
					<?php	
					elseif( $page_title == "1" || $page_title == "" ) :
						( get_the_title() )? the_title() : the_permalink();
					endif;
				else :
					if( 'post' == get_post_type() && is_single() ) :
						// get the post title toggle option
						$post_title = cyberchimps_get_option( 'single_post_title' );
						if( $post_title == "1" ) : ?>
							<?php ( get_the_title() )? the_title() : the_permalink(); 
						endif;
						else : ?>
							<a href="<?php the_permalink(); ?>" title="<?php printf( esc_attr__( 'Permalink to %s', 'one-page-business-pro' ), the_title_attribute( 'echo=0' ) ); ?>" rel="bookmark">
								<?php ( get_the_title() )? the_title() : the_permalink(); ?>
							</a>
					<?php endif;
					endif;

				echo ( 'post' == get_post_type() && !is_single() || is_search() ) ? '</h2>' : '</h1>'; ?>
			</div>
			<div class="col-lg-1">
				<?php cyberchimps_post_format_icon(); ?>
			</div>
		</div>
		<?php if ( 'post' == get_post_type() ) : ?>
			<div class="entry-meta">
				<div class="row">
					<div class="col-lg-12 main_posted_by">
						<?php cyberchimps_posted_by(); ?>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12">
						<?php cyberchimps_posted_on(); ?>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12">
						<?php cyberchimps_posted_in(); ?>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12">
						<?php cyberchimps_post_comments(); /*cyberchimps_post_format_icon();*/  ?>
					</div>
				</div>
			</div><!-- .entry-meta -->
		<?php endif; ?>
	</header><!-- .entry-header -->
  
	<?php if ( is_single() ) : // Only display Excerpts for Search ?>
  
		<div class="entry-content">
    			<?php cyberchimps_featured_image(); ?>
			<?php the_content( __( 'Continue reading', 'one-page-business-pro' ) . '<span class="meta-nav">&rarr;</span>' ); ?>
			<?php edit_post_link( __( 'Edit', 'one-page-business-pro' ), '<span class="edit-link">', '</span>' ); ?>
			<?php wp_link_pages( array( 'before' => '<div class="page-links">' . __( 'Pages:', 'one-page-business-pro' ), 'after' => '</div>' ) ); ?>
		</div><!-- .entry-content -->
    
    	<?php elseif( is_archive() ): ?>
  		<?php if( cyberchimps_get_option( 'archive_post_excerpts', 0 ) != 0 ): ?>
  			<div class="entry-summary">
      				<?php cyberchimps_featured_image(); ?>
        			<?php the_excerpt(); ?>
      			</div>
    	<?php else: ?>
    		<div class="entry-content">
    			<?php cyberchimps_featured_image(); ?>
			<?php the_content( __( 'Continue reading', 'one-page-business-pro' ) . '<span class="meta-nav">&rarr;</span>' ); ?>
			<?php wp_link_pages( array( 'before' => '<div class="page-links">' . __( 'Pages:', 'one-page-business-pro' ), 'after' => '</div>' ) ); ?>
		</div><!-- .entry-content -->
    <?php endif; ?>
		
	<?php elseif( is_search() ): ?>	
  		<div class="entry-summary">
    			<?php cyberchimps_featured_image(); ?>
    			<?php add_filter( 'excerpt_more', 'cyberchimps_search_excerpt_more', 999 ); ?>
     			 <?php add_filter( 'excerpt_length', 'cyberchimps_search_excerpt_length', 999 ); ?>
			<?php the_excerpt(); ?>
      			<?php remove_filter( 'excerpt_length', 'cyberchimps_search_excerpt_length', 999 ); ?>
      			<?php remove_filter( 'excerpt_more', 'cyberchimps_search_excerpt_more', 999 ); ?>
		</div><!-- .entry-summary -->

	<?php elseif( is_page() ): ?>
		<div class="entry-summary">
			<?php cyberchimps_featured_image(); 
				 the_content(); ?>
			<?php edit_post_link( __( 'Edit', 'one-page-business-pro' ), '<span class="edit-link">', '</span>' ); ?>
		</div><!-- .entry-summary -->
	
	<?php elseif( is_home() ) :// blog post pages ?>
  		<?php if( cyberchimps_get_option( 'post_excerpts', 0 ) != 0 ): ?>
  			<div class="entry-summary">
      				<?php cyberchimps_featured_image(); ?>
        			<?php the_excerpt(); ?>
				<?php edit_post_link( __( 'Edit', 'one-page-business-pro' ), '<span class="edit-link">', '</span>' ); ?>
      			</div>
    <?php else: ?>
    	<div class="entry-content">
    		<?php cyberchimps_featured_image(); ?>
				<?php the_content( __( 'Continue reading', 'one-page-business-pro' ) . '<span class="meta-nav">&rarr;</span>' ); ?>
				<?php edit_post_link( __( 'Edit', 'one-page-business-pro' ), '<span class="edit-link">', '</span>' ); ?>
				<?php wp_link_pages( array( 'before' => '<div class="page-links">' . __( 'Pages:', 'one-page-business-pro' ), 'after' => '</div>' ) ); ?>
			</div><!-- .entry-content -->
    <?php endif; ?>
	
	<?php else: ?>
		<div class="entry-content">
			<?php the_content(); ?>
		</div><!-- .entry-content -->
		
	<?php endif; ?>
	
		<?php if ( 'post' == get_post_type() && cyberchimps_get_option( 'post_byline_tags', 1 ) ) : // Hide category and tag text for pages on Search ?>
	<footer class="entry-meta">
    	
		<?php cyberchimps_post_tags(); ?>
		        	
	</footer><!-- #entry-meta -->
  <?php endif; // End if 'post' == get_post_type() ?>	
</article>
<?php

}
?>
