<?php
/**
 * Footer Template
 *
 * Please do not edit this file. This file is part of the CyberChimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v3.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

?>

<div id="footer">
  <div class="container">
	
		<?php do_action('cyberchimps_before_footer_container'); ?>
		<?php do_action('cyberchimps_footer'); ?>
		<?php do_action('cyberchimps_after_footer_container'); ?>
		<?php do_action('cyberchimps_after_wrapper'); ?>
	
  </div>
</div>



<?php wp_footer(); ?>

