<?php
/**
 * Header Template
 *
 * Please do not edit this file. This file is part of the CyberChimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v3.0 (or later)
 * @link     http://www.cyberchimps.com/
 */
?>
<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="description" content="">
<meta name="author" content="">

<!-- Favicons
    ================================================== -->
<link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon">
<link rel="apple-touch-icon" href="img/apple-touch-icon.png">
<link rel="apple-touch-icon" sizes="72x72" href="img/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="114x114" href="img/apple-touch-icon-114x114.png">



<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

   

<?php wp_head();
wp_enqueue_script( 'script-main', get_template_directory_uri() .'/js/main.js');
?>
</head>

<body <?php body_class(); ?>>

<div id="preloader">
  <div id="status"> <img src="<?php echo get_template_directory_uri().'/img/preloader.gif';?>" height="64" width="64" alt="Preloader"> </div>
</div>

<?php

// To enable/disable menu navigation


        
        if( !get_option('cyberchimps_options') )
        {
          $enable_service_section = 1;
          $enable_portfolio_section = 1; 
          $enable_about_section = 1;
          $enable_team_section=1;
          $enable_testimonial_section=1;
          $enable_contact_section=1;
	  $home_menu_title = "Home";
          $about_us_menu_title = "About";
          $service_menu_title = "Services";
          $team_menu_title = "Team";
          $portfolio_menu_title = "Portfolio";
          $testimonial_menu_title="Testimonial";
          $contact_menu_title = "Contact";
          $home_heading = 'We are Growing';
          $home_subheading = 'a creative digital agency from New York';
          $home_button_text = 'Our Portfolio';
	  $home_button_link = '';
	  $header_image= (get_template_directory_uri().'/img/header-bg.jpg');
	  $header_button_point='#works-section';
        }
        else
        {
          $res = get_option('cyberchimps_options');

	  $enable_service_section = (isset($res['services_option'])) ? cyberchimps_get_option('services_option') : 1 ;
		
	  $enable_portfolio_section = (isset($res['portfolio_option'])) ? cyberchimps_get_option('portfolio_option') : 1 ;
          
	  $enable_about_section = (isset($res['about_option'])) ? cyberchimps_get_option('about_option') : 1 ;
          
	  $enable_team_section = (isset($res['team_option'])) ? cyberchimps_get_option('team_option') : 1 ;
         
	  $enable_testimonial_section = (isset($res['testimonial_option'])) ? cyberchimps_get_option('testimonial_option') : 1 ;
         
	  $enable_contact_section = (isset($res['contact_option'])) ? cyberchimps_get_option('contact_option') : 1 ;

	  $home_menu_title = (isset($res['menu_title_header'])) ? cyberchimps_get_option('menu_title_header') : "Home" ;
          
	  $about_us_menu_title = (isset($res['menu_title_about'])) ? cyberchimps_get_option('menu_title_about') : "About" ;
          
	  $service_menu_title = (isset($res['menu_title_services'])) ? cyberchimps_get_option('menu_title_services') : "Services" ;
          
	  $team_menu_title = (isset($res['menu_title_team'])) ? cyberchimps_get_option('menu_title_team') : "Team" ;
          
	  $portfolio_menu_title = (isset($res['menu_title_portfolio'])) ? cyberchimps_get_option('menu_title_portfolio') : "Portfolio" ;
         
	  $testimonial_menu_title = (isset($res['menu_title_testimonial'])) ? cyberchimps_get_option('menu_title_testimonial') : "Testimonial" ;
          
	  $contact_menu_title = (isset($res['menu_title_contact'])) ? cyberchimps_get_option('menu_title_contact') : "Contact" ;
          
	  $home_heading = (isset($res['header_title'])) ? cyberchimps_get_option('header_title') : 'We are Growing' ;
          
	  $home_subheading = (isset($res['header_desc'])) ? cyberchimps_get_option('header_desc') : 'a creative digital agency from New York' ;
          
	  $home_subheading = (isset($res['header_desc'])) ? cyberchimps_get_option('header_desc') : 'a creative digital agency from New York' ;
          
          $home_button_text = (isset($res['header_button_title'])) ? cyberchimps_get_option('header_button_title') : 'Our Portfolio' ;
		
	  $header_image = (isset($res['custom_background_image_for_header'])) ? cyberchimps_get_option('custom_background_image_for_header') : (get_template_directory_uri().'/img/header-bg.jpg');

	  $header_pointer = cyberchimps_get_option('button_category');
          
	  switch($header_pointer)
	  {
		case 0:
			$header_button_point='#about-section';
			break;
		case 1:
			$header_button_point='#services-section';
			break;
		case 2:
			$header_button_point='#works-section';
			break;
		case 3:
			$header_button_point='#team-section';
			break;
		case 4:
			$header_button_point='#testimonials-section';
			break;
		case 5:
			$header_button_point='#contact-section';
			break;
		default:
			$header_button_point='#works-section';
	  }
	  
        }

?>


<!-- Navigation
    ==========================================-->
<nav id="menu" class="navbar navbar-default navbar-fixed-top">
  <div class="container"> 
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button id="menu_button" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
	<div class="head_title">
      <?php 
      if(cyberchimps_get_option('menu_title_header'))
        do_action('cyberchimps_header'); 
      else
        echo _e('<h2>One Page Business Pro</h2>');
      ?></div>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        
	            <li>
                        <a class="page-scroll" href="#home"><?php echo $home_menu_title; ?></a>
                    </li>
          <?php if($enable_about_section)
            {?>
                <li class="active">
                    <a class="page-scroll" href="#about-section"><?php echo $about_us_menu_title; ?></a>
                </li>
          <?php   } ?>
          <?php if($enable_service_section)
            {?>
                <li>
                    <a class="page-scroll" href="#services-section"><?php echo $service_menu_title; ?></a>
                </li>
          <?php   } ?>
          <?php if($enable_portfolio_section)
            {?>
                <li>
                    <a class="page-scroll" href="#works-section"><?php echo $portfolio_menu_title; ?></a>
                </li>
          <?php   } ?>
          
          <?php if($enable_team_section)
            {?>
                <li>
                    <a class="page-scroll" href="#team-section"><?php echo $team_menu_title; ?></a>
                </li>
          <?php   } ?>
          <?php if($enable_testimonial_section)
            {?>
                <li>
                    <a class="page-scroll" href="#testimonials-section"><?php echo $testimonial_menu_title; ?></a>
                </li>
          <?php   } ?>
          <?php if($enable_contact_section)
            {?>
                <li>
                    <a class="page-scroll" href="#contact-section"><?php echo $contact_menu_title; ?></a>
                </li>
          <?php   } ?>
      </ul>
    </div>
    <!-- /.navbar-collapse --> 
  </div>
  <!-- /.container-fluid --> 
</nav>


<!-- Header -->
<header class="text-center img-reponsive" id="home" style="background-image:url(<?php echo $header_image; ?>)">
  <div class="intro-text">
    <h1 class="wow fadeInDown"><?php echo $home_heading; ?></h1>
    <p class="wow fadeInDown"><?php echo $home_subheading; ?></p>

    <a href="<?php echo $header_button_point; ?>" class="btn btn-default btn-lg page-scroll wow fadeInUp" data-wow-delay="200ms"><?php echo $home_button_text; ?></a> </div>

</header>

